## Code to find avg of all temperatures taken as an input from the user.

In [8]:
n= int(input("Please enter the number of days you want to add temperatures for : "))

import numpy as np

def avg_temp(n):
    
    temps= np.ndarray([1,n])
    
    for i in range(n):
        print(temps)
        temps[0,i]= int(input(f"Please enter temp on day {i+1} : "))
    
    return (np.mean(temps, 1))

avg_temp(n)                       
        

Please enter the number of days you want to add temperatures for :  5


[[15. 25. 25. 32. 12.]]


Please enter temp on day 1 :  14


[[14. 25. 25. 32. 12.]]


Please enter temp on day 2 :  16


[[14. 16. 25. 32. 12.]]


Please enter temp on day 3 :  18


[[14. 16. 18. 32. 12.]]


Please enter temp on day 4 :  20


[[14. 16. 18. 20. 12.]]


Please enter temp on day 5 :  22


array([18.])

In [5]:
temps.shape

(1, 5)

In [ ]:
temps[1]