## Code to find avg of all temperatures taken as an input from the user.

In [14]:
n= int(input("Please enter the number of days you want to add temperatures for : "))

import numpy as np

def avg_temp(n):
    
    temps= np.ndarray([1,n])
    
    for i in range(n):
        print(temps)
        temps[0,i]= int(input(f"Please enter temp on day {i+1} : "))
    
    return (np.mean(temps, 1), temps)

mean_temp, temps=avg_temp(n)                       
        

Please enter the number of days you want to add temperatures for :  5


[[2.12199579e-314 0.00000000e+000 4.82208070e-321 9.35800144e-312
  0.00000000e+000]]


Please enter temp on day 1 :  14


[[1.40000000e+001 0.00000000e+000 4.82208070e-321 9.35800144e-312
  0.00000000e+000]]


Please enter temp on day 2 :  16


[[1.40000000e+001 1.60000000e+001 4.82208070e-321 9.35800144e-312
  0.00000000e+000]]


Please enter temp on day 3 :  18


[[1.40000000e+001 1.60000000e+001 1.80000000e+001 9.35800144e-312
  0.00000000e+000]]


Please enter temp on day 4 :  20


[[14. 16. 18. 20.  0.]]


Please enter temp on day 5 :  22


#### DAYS ABOVE AVERAGE  TEMPERATURE

In [15]:
temps

array([[14., 16., 18., 20., 22.]])

In [18]:
mean_temp

array([18.])

In [19]:
temps

array([[14., 16., 18., 20., 22.]])

In [25]:
temps[temps>mean_temp]

array([20., 22.])